repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.17
    hooks:
      - id: ruff-check
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy-check
        name: mypy check
        entry: uv run mypy
        language: system
        types: [python]
      - id: pytest
        name: pytest
        entry: uv run pytest
        language: system
        pass_filenames: false
        stages: [commit]
