name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v9.0.0
      - run: uv run pytest

  pyformat:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v9.0.0
      - run: uv run ruff format --check --diff

  pylint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v9.0.0
      - run: uv run ruff check --output-format=github

  pytypes:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v9.0.0
      - run: uv run ty check

  jscheck:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - run: npx biome ci

  publish:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    needs:
      - pytest
      - pyformat
      - pylint
      - pytypes
      - jscheck
    steps:
      - uses: actions/checkout@v7
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@main
        with:
          name: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    needs:
      - publish
    steps:
      - name: Deploy
        run: |
          IMG="${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}"
          curl -sS -X POST \
              -H "Authorization: Bearer ${{ secrets.WATCHTOWER_TOKEN }}" \
              "https://watchtower.shish.io/v1/update?images=$IMG"
